"""Food-101 英文标签 → 中文映射。

Food-101 数据集（Bossard et al. 2014）固定 101 个类别。HF `nateraw/food`
模型用的就是这套标签 ID。返回中文名给前端直接显示，省一份 RN bundle 翻译表。

缺失 fallback: zh_label("foo") → "foo"（保留英文不丢信息）
"""

from __future__ import annotations

FOOD_LABELS_ZH: dict[str, str] = {
    "apple_pie": "苹果派",
    "baby_back_ribs": "烤排骨",
    "baklava": "果仁蜜饼",
    "beef_carpaccio": "生牛肉薄片",
    "beef_tartare": "鞑靼牛肉",
    "beet_salad": "甜菜根沙拉",
    "beignets": "法式甜甜圈",
    "bibimbap": "韩式拌饭",
    "bread_pudding": "面包布丁",
    "breakfast_burrito": "早餐卷饼",
    "bruschetta": "意式烤面包",
    "caesar_salad": "凯撒沙拉",
    "cannoli": "意式奶油卷",
    "caprese_salad": "卡布里沙拉",
    "carrot_cake": "胡萝卜蛋糕",
    "ceviche": "酸橘汁腌鱼",
    "cheesecake": "芝士蛋糕",
    "cheese_plate": "奶酪拼盘",
    "chicken_curry": "咖喱鸡",
    "chicken_quesadilla": "鸡肉墨西哥卷",
    "chicken_wings": "鸡翅",
    "chocolate_cake": "巧克力蛋糕",
    "chocolate_mousse": "巧克力慕斯",
    "churros": "西班牙油条",
    "clam_chowder": "蛤蜊浓汤",
    "club_sandwich": "总会三明治",
    "crab_cakes": "蟹肉饼",
    "creme_brulee": "焦糖布丁",
    "croque_madame": "法式火腿芝士三明治",
    "cup_cakes": "杯子蛋糕",
    "deviled_eggs": "魔鬼蛋",
    "donuts": "甜甜圈",
    "dumplings": "饺子",
    "edamame": "毛豆",
    "eggs_benedict": "班尼迪克蛋",
    "escargots": "法式焗蜗牛",
    "falafel": "中东豆丸",
    "filet_mignon": "菲力牛排",
    "fish_and_chips": "炸鱼薯条",
    "foie_gras": "鹅肝",
    "french_fries": "薯条",
    "french_onion_soup": "法式洋葱汤",
    "french_toast": "法式吐司",
    "fried_calamari": "炸鱿鱼圈",
    "fried_rice": "炒饭",
    "frozen_yogurt": "冻酸奶",
    "garlic_bread": "蒜香面包",
    "gnocchi": "意大利土豆丸",
    "greek_salad": "希腊沙拉",
    "grilled_cheese_sandwich": "烤芝士三明治",
    "grilled_salmon": "烤三文鱼",
    "guacamole": "牛油果酱",
    "gyoza": "煎饺",
    "hamburger": "汉堡",
    "hot_and_sour_soup": "酸辣汤",
    "hot_dog": "热狗",
    "huevos_rancheros": "墨西哥乡村蛋",
    "hummus": "鹰嘴豆泥",
    "ice_cream": "冰淇淋",
    "lasagna": "千层面",
    "lobster_bisque": "龙虾浓汤",
    "lobster_roll_sandwich": "龙虾卷三明治",
    "macaroni_and_cheese": "芝士通心粉",
    "macarons": "马卡龙",
    "miso_soup": "味噌汤",
    "mussels": "青口贝",
    "nachos": "墨西哥玉米片",
    "omelette": "煎蛋卷",
    "onion_rings": "洋葱圈",
    "oysters": "生蚝",
    "pad_thai": "泰式炒河粉",
    "paella": "西班牙海鲜饭",
    "pancakes": "松饼",
    "panna_cotta": "意式奶冻",
    "peking_duck": "北京烤鸭",
    "pho": "越南河粉",
    "pizza": "披萨",
    "pork_chop": "猪排",
    "poutine": "加拿大肉汁奶酪薯条",
    "prime_rib": "烤牛肋排",
    "pulled_pork_sandwich": "手撕猪肉三明治",
    "ramen": "拉面",
    "ravioli": "意式饺子",
    "red_velvet_cake": "红丝绒蛋糕",
    "risotto": "意大利烩饭",
    "samosa": "印度三角饺",
    "sashimi": "刺身",
    "scallops": "扇贝",
    "seaweed_salad": "海藻沙拉",
    "shrimp_and_grits": "鲜虾玉米糊",
    "spaghetti_bolognese": "肉酱意面",
    "spaghetti_carbonara": "培根蛋意面",
    "spring_rolls": "春卷",
    "steak": "牛排",
    "strawberry_shortcake": "草莓奶油蛋糕",
    "sushi": "寿司",
    "tacos": "墨西哥玉米饼",
    "takoyaki": "章鱼烧",
    "tiramisu": "提拉米苏",
    "tuna_tartare": "鞑靼金枪鱼",
    "waffles": "华夫饼",
}

assert len(FOOD_LABELS_ZH) == 101, (
    f"Food-101 应该有 101 个类，当前 {len(FOOD_LABELS_ZH)}"
)


def zh_label(label_en: str) -> str:
    """英文 label → 中文。未命中 fallback 返回英文原文，不抛错。"""
    return FOOD_LABELS_ZH.get(label_en, label_en)
